### ISSUE TITLE
Version 4.16.0 freezes

### ISSUE THREAD

**Issue by bodhi-baum** [schadfield/shogi-explorer#3]
When I try to add hachu-0.29 to shogi-explorer it freezes and blocks the whole computer so I have to do a restart,

**Comment by schadfield** [comment]
Where do I find hachu-0.29? Does it use the USI protocol?

**Comment by bodhi-baum** [comment]
For example at [https://packages.debian.org/sid/source/hachu](url). But I was mistaken. It is hachu 0.21. Well, it is XBoard-compatible.

**Comment by schadfield** [comment]
Shogi Explorer only works with USI engines.
